PrivateChart/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
  path('admin/', admin.site.urls),
  path('accounts/', include('django.contrib.auth.urls')),
  path('accounts/', include('accounts.urls')),
  path('',include('home.urls')),
  path('chart/',include('chart.urls')),
]

chart/urls.py
from django.urls import path
from . import views

app_name = 'chart'

urlpatterns = [
    path('history/',views.history, name='history'),
    path('index/',views.chart_index, name='chart_index'),
    path('generate/',views.histories2edit, name='chart_generate'),
    path('create/',views.none2edit, name='chart_create'),
    path('add/',views.chart_add, name='chart_add'),
    path('update/<int:id>',views.chart_update, name='chart_update'),
    path('delete/<int:id>',views.chart_delete, name='chart_delete'),
    path('detail/<int:id>',views.chart_detail, name='chart_detail'),
    path('image/<int:id>',views.chart_image, name='chart_image'),
    path('review/image/<int:id>',views.chart_image_review, name='chart_image_review'),
    path('review/',views.review_index, name='review_index'),
    path('review/<int:id>',views.review, name='review'),
    path('review/<int:id>/later/<str:delta>',views.review_later, name='review_later'),
    path('review/update/<int:id>',views.review_update, name='review_update'),
    path('review/create/',views.review_create, name='review_create'),
    path('review/delete/<int:id>',views.review_delete, name='review_delete'),
    path('review/<int:id>/position/',views.speed_order, name='speed_order'),  # ReviewTableのid
    path('review/position/<int:id>',views.market_settlement, name='market_settlement'),  # PositionTableのid
    path('review/position/<int:id>/update/',views.position_update, name='position_update'),  # PositionTableのid
    path('tag/index/',views.TagListView.as_view(), name='tag_index'),
    path('tag/create/',views.TagCreateView.as_view(), name='tag_create'),
    path('tag/update/<int:pk>',views.TagUpdateView.as_view(), name='tag_update'),
    path('tag/delete/<int:pk>',views.TagDeleteView.as_view(), name='tag_delete'),
]

home/urls.py
from django.urls import path
from .views import index 

app_name = 'home'

urlpatterns = [
    path('',index,name='index'),
]

chart/models.py
from django.db import models
from django.contrib.auth.models import User
# from django.utils import timezone

KIND = (("new","新規"),("settlement","決済"))
BUY_SELL = (("buy","買"),("sell","売"))
STATE = (("accepted","受付済"),("executed","約定済"),("canceled","取消済"))
CONDITION = (("limit","指値"),("stop","逆指値"),("market","成行"))
RULE = (
  ("1T","1分足"),
  ("3T","3分足"),
  ("5T","5分足"),
  ("10T","10分足"),
  ("15T","15分足"),
  ("30T","30分足"),
  ("1H","1時間足"),
  ("4H","4時間足"),
  ("D","日足"),
)
PAIR = (
  ("USD/JPY", "USD/JPY"),
  ("EUR/JPY","EUR/JPY"),
  ("EUR/USD","EUR/USD"),
  ("GBP/JPY","GBP/JPY"),
  ("AUD/JPY","AUD/JPY")
)
COLOR = (
  ("#FF0000","赤"),
  ("#FFA500","オレンジ"),
  ("#FFFF00","黄"),
  ("#00FF00","緑"),
  ("#ADFF2F","黄緑"),
  ("#00FFFF","水色"),
  ("#FF00FF","紫"),
  ("#FFE4E1","デフォルト"),
)

class TagTable(models.Model):
  user = models.ForeignKey(User,on_delete=models.CASCADE)
  name = models.CharField(max_length=255)
  memo = models.TextField(null=True, blank=True)
  color = models.CharField(max_length=31,null=True, blank=True, choices=COLOR, default="#FFE4E1")
  def __str__(self):
    return self.name

class HistoryTable(models.Model):
  user = models.ForeignKey(User,on_delete=models.CASCADE)
  account = models.CharField(max_length=50)
  order_number = models.IntegerField()
  pair = models.CharField(max_length=10)  # choicesは利用しない
  order_type  = models.CharField(max_length=20)
  kind = models.CharField(max_length=10, choices=KIND)
  buy_sell = models.CharField(max_length=10, choices=BUY_SELL)
  quantity = models.FloatField()
  state = models.CharField(max_length=10, choices=STATE)
  revocation_reason = models.CharField(max_length=10, null=True, blank=True)  # 失効理由(ほぼOCO)
  order_datetime = models.DateTimeField()
  order_rate = models.FloatField(null=True, blank=True)
  condition = models.CharField(max_length=10, choices=CONDITION)
  execution_datetime = models.DateTimeField(null=True, blank=True)
  execution_rate = models.FloatField(null=True, blank=True)
  unit = models.CharField(max_length=10,default="JPY")
  profit = models.FloatField(null=True, blank=True)
  swap = models.FloatField(null=True, blank=True)
  memo = models.CharField(max_length=511)
  class Meta:
    constraints = [
      models.UniqueConstraint(
        fields=["user", "account", "order_number"],
        name="history_unique"
      )
    ]
  
def default_chart_name():
    last_review = ReviewTable.objects.last()
    next_id = last_review.id + 1 if last_review else 1
    return f"チャート（{next_id}）"

class ChartTable(models.Model):
  user = models.ForeignKey(User,on_delete=models.CASCADE)
  # name = models.CharField(max_length=255, default=timezone.datetime.now().strftime("%Y/%m/%d %H:%M:%S"))
  name = models.CharField(max_length=255, default=default_chart_name)
  # pair = models.CharField(max_length=10, choices=PAIR)
  pair = models.CharField(max_length=10)
  rule = models.CharField(max_length=10, choices=RULE)
  standard_datetime = models.DateTimeField()
  minus_delta = models.IntegerField(default=100)
  tags = models.ManyToManyField(TagTable, related_name="chart_tags", blank=True)
  plus_delta = models.IntegerField(default=100)
  memo = models.TextField(null=True, blank=True)
  def __str__(self):
    return self.name

class HistoryLinkTable(models.Model):
  chart = models.ForeignKey(ChartTable, on_delete=models.CASCADE)
  history = models.ForeignKey(HistoryTable, on_delete=models.CASCADE)

def default_review_name():
    last_review = ReviewTable.objects.last()
    next_id = last_review.id + 1 if last_review else 1
    return f"レビュー（{next_id}）"

class ReviewTable(models.Model):
  user = models.ForeignKey(User,on_delete=models.CASCADE)
  # name = models.CharField(max_length=255, default=timezone.datetime.now().strftime("%Y/%m/%d %H:%M:%S"))
  name = models.CharField(max_length=255, default=default_review_name)
  pair = models.CharField(default="USD/JPY", max_length=10, choices=PAIR)
  rule = models.CharField(default="15T", max_length=10, choices=RULE)
  delta = models.IntegerField(default=150)
  dt = models.DateTimeField()
  memo = models.CharField(max_length=511,null=True, blank=True)

class PositionTable(models.Model):
  review = models.ForeignKey(ReviewTable, on_delete=models.CASCADE)
  pair = models.CharField(max_length=10, choices=PAIR)
  quantity = models.FloatField()
  buy_sell = models.CharField(max_length=10, choices=BUY_SELL)
  position_datetime = models.DateTimeField()
  position_rate = models.FloatField()
  condition = models.CharField(max_length=10, choices=CONDITION, null=True, blank=True)
  limit = models.FloatField(null=True, blank=True)
  stop = models.FloatField(null=True, blank=True)
  profit = models.IntegerField(null=True, blank=True)
  settlement_datetime = models.DateTimeField(null=True, blank=True)
  settlement_rate = models.FloatField(null=True, blank=True)

chart/views.py
# 基本
import sys
import os
import pandas as pd
import datetime
from pytz import timezone
# django
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse
from django.db.models import Avg
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.urls import reverse, reverse_lazy
from django.db.models import Q
from django.db.models import Sum
from django.conf import settings
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin
# modelsとforms
from .models import HistoryTable, ChartTable, HistoryLinkTable, ReviewTable, PositionTable, TagTable
from .forms import ChartForm, ReviewForm, ReviewUpdateForm, PositionSpeedForm, PositionMarketForm, PositionUpdateForm
# 独自関数
sys.path.append(os.path.join(os.path.dirname(__file__), '..'))
import lib.chart
import lib.chart_settings
# チャート出力用
import io
import base64
from matplotlib import use
use("Agg")
import mplfinance as mpf

import pandas_datareader.data as web
import yfinance as yf
yf.pdr_override()

# 曜日変換要
WEEK = ("月","火","水","木","金","土","日")

# html用
history_header = [
  "アカウント",
  "注文番号",
  "取引種類",
  "通貨ペア",
  "売買",
  "注文タイプ",
  "取引数量",
  "状態",
  "失効理由",
  "注文日時",
  "注文レート",
  "執行条件",
  "約定日時",
  "約定レート",
  "決済損益",
  "スワップ",
]
history_width = [
  100,  # アカウント
  80,  # 注文番号
  100,  # 取引種類
  100,  # 通貨ペア
  50,  # 売買
  100,  # 注文タイプ
  80,  # 取引数量
  100,  # 状態
  80,  # 失効理由
  200,  # 注文日時
  100,  # 注文レート
  80,  # 執行条件
  200,  # 約定日時
  100,  # 約定レート
  100,  # 決済損益
  100  # スワップ
]

RATE_DIR = os.path.join(os.path.dirname(__file__), "../data/rate") 


class TagListView(LoginRequiredMixin, ListView):
  template_name = 'chart/tag_index.html'
  def get_queryset(self):
    user = self.request.user
    print(len(TagTable.objects.filter(user=user)))
    return TagTable.objects.filter(user=user)

class TagCreateView(LoginRequiredMixin, CreateView):
  model = TagTable
  fields = ('name','memo', 'color')
  template_name = 'chart/tag_edit.html'
  success_url = reverse_lazy('chart:tag_index')
  def form_valid(self, form):
    form.instance.user = self.request.user
    return super(TagCreateView, self).form_valid(form)
  def get_context_data(self):
    context = super().get_context_data()
    context["edit_type"] = "create"
    return context

class TagUpdateView(LoginRequiredMixin, UpdateView):
  model = TagTable
  fields = ('name','memo', 'color')
  template_name = 'chart/tag_edit.html'
  success_url = reverse_lazy('chart:tag_index')
  def get_context_data(self):
    context = super().get_context_data()
    context["edit_type"] = "update"
    return context

class TagDeleteView(LoginRequiredMixin, DeleteView):
  model = TagTable
  template_name = 'chart/tag_delete.html'
  success_url = reverse_lazy('chart:tag_index')

@login_required
def history(request):
  histories_all = HistoryTable.objects.filter(user=request.user).order_by("-order_number","-order_datetime")
  per_page = request.GET.get('per_page', 50)
  paginator = Paginator(histories_all, per_page)
  page = request.GET.get('page')
  histories = paginator.get_page(page)
  context = {
    "histories":histories, 
    "header":history_header, 
    "width":history_width,
    "box":True, 
    "checked":False
  }
  return render(request, 'chart/history.html', context)

@login_required
def chart_index(request):
  _charts = ChartTable.objects.filter(user=request.user).order_by("-id")
  links = [HistoryLinkTable.objects.filter(chart=i).count() for i in _charts]
  header = [
    "登録名",
    "タグ",
    "通貨ペア",
    "足",
    "基準日時",
    "新規+決済",
    "操作"
  ]
  width = [
  200,  # 登録名
  200, # タグ
  100,  # 通貨ペア
  50,  # 足
  200,  # 基準日時
  100,  # 新規+決済
  100  # 操作
  ]
  context = {"charts":_charts, "links":links, "header":header, "width":width, "box":False, "checked":False}
  return render(request, 'chart/chart_index.html', context)

@login_required
def chart_image(request,id, _HttpResponse=True, _chart=None, histories=None):
  # 該当のchartのデータを取得
  if _chart == None:
    _chart = get_object_or_404(ChartTable, pk=id)
  # 該当のチャートと紐付けられている取引履歴を取得
  if histories == None:
    histories = [i.history for i in HistoryLinkTable.objects.filter(chart=_chart)]
    histories = sorted(histories, reverse=True, key=lambda x: x.id)
    histories = sorted(histories, reverse=True, key=lambda x: x.order_datetime)
  # 為替データを取得
  # daysは要調整
  if "H" in _chart.rule:
    days = 60
  elif "D" in _chart.rule:
    days = 240
  elif _chart.rule[-1] == "T":
    minutes = int(_chart.rule[:-1])
    if minutes <= 3:
      days = 4
    elif minutes <= 15:
      days = 7
    else:
      days = 10
  else:
    print("Warning: chart_image: rule may not be valid")
    days = 10
  start_date = (_chart.standard_datetime-datetime.timedelta(days=days)).date()
  end_date = (_chart.standard_datetime+datetime.timedelta(days=days)).date()
  df = lib.chart.GMO_dir2DataFrame(
    os.path.join(os.path.dirname(__file__), "../data/rate"), 
    pair=_chart.pair,
    date_range=[
      start_date,end_date
    ],
    guarantee=True
  ) 
  if df is None:
    yf = True
  else:
    yf = False
    # 足を変換
    df = lib.chart.resample(df, _chart.rule)
    if len(df)<_chart.plus_delta+_chart.minus_delta+60:  # 要調整
      yf = True
  if yf:
    interval = _chart.rule.replace("T", "m").replace("H", "h").replace("D", "d")
    if interval not in ["1m", "2m", "5m", "15m", "30m", "60m", "90m", "1h", "1d"]:
      resample = True
      interval = str(1)+interval[-1]
    else:
      resample = False
    if "^" in _chart.pair:
      ticker = _chart.pair
    else:
      ticker = f'{_chart.pair.replace("/","")}=X'
    # daysは要調整
    if interval == "1m":
      days = 3
    elif interval == "2m":
      days = 5
    elif interval == "5m":
      days = 10
    elif interval in ["15m", "30m"]:
      days = 25
    elif interval in ["60m", "90m", "1h"]:
      days = 50
    else:
      days = 240
    start_datetime = _chart.standard_datetime-datetime.timedelta(days=days)
    end_datetime = _chart.standard_datetime+datetime.timedelta(days=days)
    end_datetime = min(end_datetime, datetime.datetime.now(timezone(settings.TIME_ZONE))-datetime.timedelta(minutes=1))
    df = web.get_data_yahoo(tickers=ticker,start=start_datetime, end=end_datetime, interval=interval)
    if df.index[0].tzinfo is None:
      df.index = df.index.tz_localize('UTC')
    df.index = df.index.tz_convert('Asia/Tokyo')
    if resample:
      df = chart.chart.resample(df, _chart.rule)

  if yf:
    print("get data from yahoo finance")
  else:
    print("get data from GMO")
  # テクニカル指標を追加
  df = lib.chart_settings.add_technical_columns(df)
  # 最もstandard_datetimeに近い列の周辺のデータを取得する
  target_datetime = pd.Timestamp(_chart.standard_datetime)
  # nearest_index = (pd.DataFrame(df.index) - target_datetime).abs().idxmin().date
  nearest_index = (pd.DataFrame(df.index) - target_datetime).abs().idxmin().Datetime
  start_index = max(0, nearest_index - _chart.minus_delta)
  end_index = min(nearest_index + _chart.plus_delta, len(df) - 1)
  df = df.iloc[start_index:end_index+1]
  
  ### チャートを作成
  # 共通部分
  plot_args = lib.chart_settings.plot_args.copy()
  # テクニカル指標を追加
  plot_args =  lib.chart_settings.add_technical_lines(plot_args, df)
  # 横線
  hlines=dict(hlines=[],colors=[],linewidths=[])
  for history in histories:
    if history.order_rate != None:
      hlines["hlines"].append(history.order_rate)
      if history.state == "canceled":
        hlines["colors"].append("#7d7d7d")
      elif history.buy_sell == "buy":
        hlines["colors"].append("r")
      else:
        hlines["colors"].append("b")
      hlines["linewidths"].append(0.1)
  plot_args["hlines"] = hlines
  # 取引期間
  # execution = [i.execution_datetime for i in histories if i.execution_datetime != None]
  # if len(execution) >= 2:
  #   transaction_start=pd.Timestamp(min(execution).astimezone(timezone("Asia/Tokyo")).strftime("%Y-%m-%d %H:%M"),tz=timezone("Asia/Tokyo"))
  #   transaction_end=pd.Timestamp(max(execution).astimezone(timezone("Asia/Tokyo")).strftime("%Y-%m-%d %H:%M"),tz=timezone("Asia/Tokyo"))
  #   dates_df = pd.DataFrame(df.index)
  #   where_values = pd.notnull(dates_df[(dates_df>=transaction_start)&(dates_df<=transaction_end)])['date'].values
  #   max_value = df["bb_up_3"].max(),
  #   min_value = df["bb_down_3"].min(),
  #   plot_args["fill_between"] = dict(y1=max_value, y2=min_value, where=where_values, alpha=0.3) 
  # 縦線
  vlines=dict(vlines=[],colors=[],linewidths=[])
  for history in histories:
    if history.execution_datetime != None and history.state != "canceled" and history.order_rate != None:
      vlines["vlines"].append(history.execution_datetime)
      if history.buy_sell == "buy":
        vlines["colors"].append("r")
      else:
        vlines["colors"].append("b")
      vlines["linewidths"].append(0.1)
  plot_args["vlines"] = vlines
  # 画像の大きさ
  plot_args["figsize"] = (14,8)
  # plot_args["figratio"] = (10,6)
  # 画像の出力先
  buf = io.BytesIO()
  plot_args["savefig"] = {'fname':buf,'dpi':100}
  # 出力
  mpf.plot(df, **plot_args)
  buf.seek(0)
  if _HttpResponse:
    return HttpResponse(buf, content_type='image/png')
  else:
    image_data = base64.b64encode(buf.getvalue()).decode("utf-8")
    return image_data
    # htmldjangoにおいて以下のように記述することで出力できる:
    # <img src="data:image/png;base64,{{ image_data  }}" alt="Chart">

@login_required
def chart_detail(request, id):
  # 該当のchartのデータを取得
  _chart = get_object_or_404(ChartTable, pk=id)
  form = ChartForm(instance=_chart)
  # 該当のチャートと紐付けられている取引履歴を取得
  histories = [i.history for i in HistoryLinkTable.objects.filter(chart=_chart)]
  histories = sorted(histories, reverse=True, key=lambda x: x.id)
  histories = sorted(histories, reverse=True, key=lambda x: x.order_datetime)
  image_data = chart_image(request, id, _HttpResponse=False, _chart=_chart, histories=histories)
  ### 渡すもの
  context = {
    "id": id,
    "chart":_chart,
    "histories":histories, 

templates/chart/chart_detail.html
{% extends 'base.html' %}
{% block title %}チャート{% endblock title %}
{% block content %}
<div class="container-fluid custom-container">
  <div class="row">
    <div class="col-9">
      <h3 class="text-center">{{ chart.pair }} {{ chart.get_rule_display }}</h3>
      <div class="col" style="overflow-x: auto;">
        <a href="{% url "chart:chart_image" id %}">
           <img src="data:image/png;base64,{{ image_data  }}" alt="Chart">
        </a>
      </div>
    </div>
    <div class="col">
      <form class="" action="{% url 'chart:chart_update' id %}" method="post">
        {% csrf_token %}
        {# {{ form.as_p }} #}
        <p>
          保存名：{{ form.name }}
        </p>
        <p>
          基準時刻：{{ form.standard_datetime }}
        </p>
        <p>
          足：{{ form.rule }}
        </p>
        <p>
          通貨ペア：{{ form.pair }}
        </p>
        <p>
          正方向表示本数：{{ form.plus_delta }}
        </p>
        <p>
          負方向表示本数：{{ form.minus_delta }}
        </p>
        <p>
          タグ：{{ form.tags }}
        <p>
          説明：
        </p>
          {{ form.memo }}
        <p>
          <button type="submit" class="btn btn-primary btn-sm">更新</button>
          <a href="{% url 'chart:chart_delete' id %}" class="btn btn-danger btn-sm">削除</a>
        </p>
      </form>
    </div>
  </div>
</div>
{% include 'chart/history_table_jp.html' %}
{% endblock content %}

templates/chart/chart_index.html
{% extends 'base.html' %}
{% load boost %}

{% block title %}チャート一覧{% endblock title %}
{% block content %}
<h1>チャート</h1><nobr>
<a href='{% url "chart:chart_create" %}' class="btn btn-success btn">新規作成</a>
<div class="table-responsive">
  <table class="table table-bordered border-dark text-nowrap" style="table-layout:fixed;">
    <tbody>
      <tr class="table-warning text-center">
        {% for h,w in header|zip:width %}
        <th scope="col" style="width: {{ w }}px;">
            {{ h }}
        </th>
        {% endfor %}
      </tr>
      {% for chart,link in charts|zip:links %}
      <tr class="text-center">
        <td>
          {{ chart.name }}
        </td>
        <td>
          {% for tag in chart.tags.all %}
          <span class="btn btn-sm" style="background-color: {{ tag.color }}">{{ tag.name }}</span>
          {% endfor %}
        <td>
          {{ chart.pair }}
        </td>
        <td>
          {{ chart.rule }}
        </td>
        <td>
          {{ chart.standard_datetime }}
        </td>
        <td>
          {{ link }}
        </td>
        <td>
          <a href='{% url "chart:chart_detail" chart.id %}' class="btn btn-sm btn-danger btn">開く</a>
        </td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>


{% endblock content %}

templates/chart/chart_tab.html
<ul class="nav nav-tabs" id="myTab" role="tablist">
  {% for tab_name in chart_tabs %}
  <li class="nav-item" role="presentation">
    {% if forloop.counter == 1 %}
    <button
      class="nav-link active"
      id="home-tab"
      data-bs-toggle="tab"
      data-bs-target="#tab{{ forloop.counter }}"
      type="button"
      role="tab"
      aria-controls="home"
      aria-selected="true"
    >
    {% else %}
    <button
      class="nav-link"
      id="profile-tab"
      data-bs-toggle="tab"
      data-bs-target="#tab{{ forloop.counter }}"
      type="button"
      role="tab"
      aria-controls="profile"
      aria-selected="false"
    >
    {% endif %}
    {{ tab_name }}
    </button>
  </li>
  {% endfor %}
</ul>
<div class="tab-content" id="myTabContent">
  {% for head, url, image in chart_bodys %}
  {% if forloop.counter == 1 %}
  <div
    class="tab-pane fade show active"
    id="tab{{ forloop.counter }}"
    role="tabpanel"
    aria-labelledby="home-tab"
  >
  {% else %}
  <div
    class="tab-pane fade"
    id="tab{{ forloop.counter }}"
    role="tabpanel"
    aria-labelledby="profile-tab"
  >
  {% endif %}
    {% if image == None %}
    データが存在しません．
    {% else %}
    <h4 class="text-center">{{ head }}</h4>
    <a href="{{ url }}">
      <img src="data:image/png;base64,{{ image }}" alt="Chart">
    </a>
    {% endif %}
  </div>
  {% endfor %}
</div>

templates/chart/edit.html
{% extends 'base.html' %}
{% block title %}新規作成{% endblock title %}
{% block content %}
<h1>新規作成</h1>
<form class="" action="{% url 'chart:chart_add' %}" method="post">
  {% csrf_token %}
  {{ form.as_p }}
  {% if table %}
  {% include 'chart/history_table_jp.html' %}
  {% endif %}
  <button type="submit" class="btn btn-primary btn-sm">登録</button>
</form>
{% endblock content %}

templates/chart/history.html
{% extends 'base.html' %}
{% block title %}取引履歴{% endblock title %}
{% block content %}
<h1>取引履歴</h1>
{% include 'chart/per_page.html' %}
{% include 'chart/history_paginator.html' %}
<form class="" action='{% url "chart:chart_generate" %}' method="post">
{% include 'chart/history_table_jp.html' %}
</form>
{% include 'chart/history_paginator.html' %}
{% endblock content %}

templates/chart/history_paginator.html
<div class="pagination">
  <span class="step-links">
    {% if histories.has_previous %}
      <a href="?page=1">&laquo; 最初</a>
      <a href="?page={{ histories.previous_page_number }}">前へ</a>
    {% endif %}
    <span class="current">
      ページ {{ histories.number }} / {{ histories.paginator.num_pages }}
    </span>
    {% if histories.has_next %}
      <a href="?page={{ histories.next_page_number }}">次へ</a>
      <a href="?page={{ histories.paginator.num_pages }}">最後 &raquo;</a>
    {% endif %}
  </span>
</div>

templates/chart/per_page.html
<form method="get">
  <select name="per_page" onchange="this.form.submit()">
    <option value="50" {% if request.GET.per_page == "50" %}selected{% endif %}>50件/ページ</option>
    <option value="100" {% if request.GET.per_page == "100" %}selected{% endif %}>100件/ページ</option>
    <option value="200" {% if request.GET.per_page == "200" %}selected{% endif %}>200件/ページ</option>
  </select>
</form>

templates/chart/review_create.html
{% extends 'base.html' %}
{% block title %}レビュー作成{% endblock title %}
{% block content %}
<form class="" action="{% url 'chart:review_create' %}" method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit" class="btn btn-primary btn-sm">保存</button>
</form>
{% endblock content %}

templates/chart/review_index.html
{% extends 'base.html' %}
{% load boost %}

{% block title %}レビュー一覧{% endblock title %}
{% block content %}
<h1>レビュー</h1><nobr>
<a href='{% url "chart:review_create" %}' class="btn btn-success btn">新規作成</a>
{% for review in reviews %}
<div class="card">
  <h5 class="card-header">{{ review.dt }}</h5>
  <div class="card-body">
    <h5 class="card-title">{{ review.name }}</h5>
    <p class="card-text">{{ review.memo }}</p>
    <a href="{% url 'chart:review' review.id %}" class="btn btn-primary">開く</a>
  </div>
</div>
{% endfor %}

{% endblock content %}

templates/chart/tag_delete.html
{% extends "base.html" %}
{% block title %}削除{% endblock title %}
{% block content %}
  <h1>{{ object.name }}を削除しますか？</h1>
  <form method="post">
    {% csrf_token %}
    <button class="btn btn-danger btn-sm" type="submit">削除</button>
    <a href="{% url 'chart:tag_index' %}" class="btn btn-secondary btn-sm">キャンセル</a>
  </form>
{% endblock %}

templates/chart/tag_edit.html
{% extends 'base.html' %}
{% block title %}新規作成{% endblock title %}
{% block content %}
{% if edit_type == 'create' %}
<h1>新規作成</h1>
{% elif edit_type == 'update' %}
<h1>編集</h1>
{% endif %}
<form method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit" class="btn btn-primary btn-sm">登録</button>
  {% if edit_type == 'update' %}
  <a href="{% url 'chart:tag_delete' object.id %}" class="btn btn-danger btn-sm">削除</a>
  {% endif %}
  <a href="{% url 'chart:tag_index' %}" class="btn btn-secondary btn-sm">一覧に戻る</a>
</form>
{% endblock content %}

templates/chart/tag_index.html
{% extends 'base.html' %}
{% load boost %}

{% block title %}タグ一覧{% endblock title %}
{% block content %}
<h1>タグ</h1>
<a href='{% url "chart:tag_create" %}' class="btn btn-success btn">新規作成</a>
{% for tag in object_list %}
{% if tag.color %}
<div class="card" style="background-color: {{ tag.color }};">
{% else %}
<div class="card">
{% endif %}
  <div class="card-body">
    <h5 class="card-title">{{ tag.name }}</h5>
    <p class="card-text">{{ tag.memo }}</p>
    <a href="{% url 'chart:tag_update' tag.id %}" class="btn btn-primary btn-sm">編集</a>
    <a href="{% url 'chart:tag_delete' tag.id %}" class="btn btn-danger btn-sm">削除</a>
  </div>
</div>
{% endfor %}
{% endblock content %}