PrivateChart/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
  path('admin/', admin.site.urls),
  path('accounts/', include('django.contrib.auth.urls')),
  path('accounts/', include('accounts.urls')),
  path('',include('home.urls')),
  path('chart/',include('chart.urls')),
]

chart/urls.py
from django.urls import path
from . import views

app_name = 'chart'

urlpatterns = [
    path('history/',views.history, name='history'),
    path('index/',views.chart_index, name='chart_index'),
    path('generate/',views.histories2edit, name='chart_generate'),
    path('create/',views.none2edit, name='chart_create'),
    path('add/',views.chart_add, name='chart_add'),
    path('update/<int:id>',views.chart_update, name='chart_update'),
    path('delete/<int:id>',views.chart_delete, name='chart_delete'),
    path('detail/<int:id>',views.chart_detail, name='chart_detail'),
    path('image/<int:id>',views.chart_image, name='chart_image'),
    path('review/image/<int:id>',views.chart_image_review, name='chart_image_review'),
    path('review/',views.review_index, name='review_index'),
    path('review/<int:id>',views.review, name='review'),
    path('review/<int:id>/later/<str:delta>',views.review_later, name='review_later'),
    path('review/update/<int:id>',views.review_update, name='review_update'),
    path('review/create/',views.review_create, name='review_create'),
    path('review/delete/<int:id>',views.review_delete, name='review_delete'),
    path('review/<int:id>/position/',views.speed_order, name='speed_order'),  # ReviewTableのid
    path('review/position/<int:id>',views.market_settlement, name='market_settlement'),  # PositionTableのid
    path('review/position/<int:id>/update/',views.position_update, name='position_update'),  # PositionTableのid
    path('tag/index/',views.TagListView.as_view(), name='tag_index'),
    path('tag/create/',views.TagCreateView.as_view(), name='tag_create'),
    path('tag/update/<int:pk>',views.TagUpdateView.as_view(), name='tag_update'),
    path('tag/delete/<int:pk>',views.TagDeleteView.as_view(), name='tag_delete'),
]

home/urls.py
from django.urls import path
from .views import index 

app_name = 'home'

urlpatterns = [
    path('',index,name='index'),
]

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    
    <!-- Custom CSS -->
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">

    <title>{% block title %}{% endblock title %}</title>
  </head>
  <body>
    <nav class="navbar navbar-expand navbar-dark bg-dark fixed-top" aria-label="Second navbar example">
      <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'home:index' %}">ホーム</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarsExample02" aria-controls="navbarsExample02" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
        <div class="collapse navbar-collapse" id="navbarsExample02">
          <!-- <ul class="navbar-nav me-auto"> -->
	        <ul class="navbar-nav me-auto">
	          <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="{% url 'chart:history' %}">取引履歴</a>
	          </li>
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="{% url 'chart:chart_index' %}">チャート</a>
            </li>
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="{% url 'chart:tag_index' %}">タグ</a>
            </li>
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="{% url 'chart:review_index' %}">レビュー</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'admin:index' %}">管理</a>
            </li>
            {# <li class="nav-item"> #}
	            {# <a class="nav-link" href="#">Link</a> #}
            {# </li> #}
          </ul>
          <ul class="navbar-nav ml-auto">
            <li class="nav-item">
              <a
                class="nav-link"
                href="https://fx.click-sec.com/neo/web/trade"
                target="_blank"
                rel="noopener noreferrer"
              >
                GMOクリック証券-FXネオ
              </a>
            </li>
            {% if user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'logout' %}">{{ user }} - Logout</a>
            </li>
            {% else %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'login' %}">Login</a>
            </li>
            {% endif %}
          </ul>
					<!-- <form> -->
						<!-- <input class="form-control" type="text" placeholder="Search" aria-label="Search"> -->
					<!-- </form> -->
				</div>
			</div>
		</nav>
    <div class="padding-top">
		  {% block content %}{% endblock content %}
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    {% block extra_js %}{% endblock extra_js %}
  </body>
</html>